apps/tunduk/urls.py
from django.urls import path

from .views import (TundukController,
                    InfocomRequestedList, InfocomRequestedDetail, UnaaRequestedList,
                    UnaaRequestedDetail, MinjystRequestedList, MinjystRequestedDetail,
                    KadastrRequestedDetail, KadastrRequestedList, PersonalInfo, MinSelXozRequestedList,
                    MinSelXozRequestedDetail)

app_name = 'tunduk'

urlpatterns = [
    path('', TundukController.as_view(),
         name='tunduk-controller'),
    path('tunduk-request/', PersonalInfo.as_view(),
         name='tunduk-request'),

    # Инфоком
    path('infocom-list/', InfocomRequestedList.as_view(),
         name='infocom-list'),
    path('infocom-request-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         InfocomRequestedDetail.as_view(),
         name='infocom-detail'),
    path('infocom-request/',
         InfocomRequestedDetail.as_view(),
         name='infocom-post'),

    # Унаа
    path('unaa-list/', UnaaRequestedList.as_view(),
         name='unaa-list'),
    path('unaa-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         UnaaRequestedDetail.as_view(),
         name='unaa-detail'),
    path('unaa-info/', UnaaRequestedDetail.as_view(),
         name='unaa-post'),

    # Министерство Юстиции
    path('minjyst-list/', MinjystRequestedList.as_view(),
         name='minjyst-list'),
    path('minjyst-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         MinjystRequestedDetail.as_view(),
         name='minjyst-detail'),
    path('minjyst-info/', MinjystRequestedDetail.as_view(),
         name='minjyst-post'),

    # Кадастр
    path('kadastr-list/', KadastrRequestedList.as_view(),
         name='kadastr-list'),
    path('kadastr-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         KadastrRequestedDetail.as_view(),
         name='kadastr-detail'),
    path('kadastr-info/', KadastrRequestedDetail.as_view(),
         name='kadastr-post'),

    # Мин сель хоз
    path('minselxoz-list/', MinSelXozRequestedList.as_view(),
         name='minselxoz-list'),
    path('minselxoz-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         MinSelXozRequestedDetail.as_view(),
         name='minselxoz-detail'),
    path('minselxoz-info/', MinSelXozRequestedDetail.as_view(),
         name='minselxoz-post'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from apps.accounts.views import reset_password_view

urlpatterns = [
    path('upr/admin/accounts/reset-password/<int:user_id>/', reset_password_view, name='reset_password'),
    path('upr/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.tunduk.urls', namespace='tunduk')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tunduk/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(
        'Название компании',
        max_length=300
    )
    client_id = models.CharField(
        'ID клиента',
        help_text='ID клиента в тундук, пример: ak_jol_2000',
        max_length=150,
    )
    infocom_secret_key = models.CharField(
        'Секретный ключ клиента',
        help_text='Секретный ключ выдаваемый от Инфоком',
        max_length=150,
    )
    ip_addr = models.CharField(
        'IP Адрес',
        help_text='IP Адрес сервера тундук',
        max_length=30,
    )
    member_code = models.CharField(
        'Код участника тундук',
        help_text='Код участника тундук, пример: 60000165',
        max_length=30,
    )
    subsystem_code = models.CharField(
        'Название участника в тундук',
        help_text='Название участника передаваемый от тундук, пример: akzhol_subsystem',
        max_length=100
    )
    infocom = models.BooleanField(
        default=True,
        verbose_name='Инфоком',
    )
    unaa = models.BooleanField(
        default=False,
        verbose_name='Унаа',
    )
    minjyst = models.BooleanField(
        default=False,
        verbose_name='Мин. Юст',
    )
    kadastr = models.BooleanField(
        default=False,
        verbose_name='Кадастр',
    )
    minselxoz = models.BooleanField(
        default=False,
        verbose_name='Мин. Сель. Хоз',
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

apps/tunduk/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.tunduk.models import Company


class InfocomForm(forms.Form):
    inn = forms.CharField(label='ИНН', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите инн",
            "class": "form-group",
        }
    ))
    passport_series = forms.CharField(label='Серия паспорта', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите номер паспорта",
            "class": "form-group",
        }
    ))
    passport_number = forms.CharField(label='Номер паспорта', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите инн",
            "class": "form-group",
        }
    ))


class INNForm(forms.Form):
    inn = forms.CharField(label='ИНН', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите ИНН",
            "class": "form-group",
        }
    ))


class ENICodeForm(forms.Form):
    eni_code = forms.CharField(label='Код ЕНИ', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите код ЕНИ",
            "class": "form-group",
        }
    ))

    def clean(self):
        super().clean()

        if eni_code := self.cleaned_data.get('eni_code'):
            self.cleaned_data['eni_code'] = eni_code.replace('-', '')

        if not self.cleaned_data['eni_code'].isdigit():
            raise ValidationError('Введите только цифры')

        return self.cleaned_data


class PasswordInputWidget(forms.TextInput):
    input_type = 'password'


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        widgets = {
            'infocom_secret_key': PasswordInputWidget(),
        }

apps/tunduk/views.py
from abc import ABC

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views.generic import TemplateView, ListView, DetailView

from apps.tunduk.forms import InfocomForm, INNForm, ENICodeForm

from apps.history.models import TundukRequestLog

from utils.tunduk.infocom import Infocom
from utils.tunduk.kadastr import Kadastr
from utils.tunduk.minSelXoz import MinSelXoz
from utils.tunduk.tunduk_request_log import tunduk_request_logic
from utils.tunduk.unaa import Unaa
from utils.tunduk.minjyst import Minjyst
from utils.utils import byte_to_file


class TundukController(LoginRequiredMixin, TemplateView):
    template_name = 'tunduk/controller.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Retrieve messages from the messages framework
        messages_list = messages.get_messages(self.request)

        # Pass the messages to the context
        context['messages'] = messages_list

        return context


class PersonalInfo(LoginRequiredMixin, TemplateView):
    template_name = 'tunduk/personal_info.html'
    form = InfocomForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['form'] = InfocomForm()
        context['unaa_form'] = INNForm()
        context['eni_form'] = ENICodeForm()

        return context


class TundukAbstractList(ABC, LoginRequiredMixin, ListView):
    model = TundukRequestLog
    template_name = 'tunduk/request_list.html'

    def get_queryset(self):
        queryset = TundukRequestLog.objects.filter(
            user=self.request.user
        ).order_by('-created_at')
        return queryset


class InfocomRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.INFOCOM)
        return qs


class UnaaRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.UNAA)
        return qs


class MinjystRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.MINJYST)
        return qs


class KadastrRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.KADASTR)
        return qs


class MinSelXozRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.MINSELXOZ)
        return qs


class TundukAbstractClass(ABC, LoginRequiredMixin, DetailView):
    model = TundukRequestLog
    template_name = 'tunduk/request_detail.html'


class InfocomRequestedDetail(TundukAbstractClass):

    def post(self, request, *args, **kwargs):
        form = InfocomForm(request.POST, request.FILES)

        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            infocom = Infocom('bankPinService', user=request.user)
            result, response = infocom.post_bankPinService(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте контакт, серию и номер')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         infocom)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(
                        request,
                        result,
                        infocom,
                        result.pop('image'),
                        full_name=f'ФИО: {result.get("surname")} {result.get("name")} {result.get("patronymic")},'
                                  f'ИНН: {result.get("pin")}',
                        wallet=True
                    )

                    return HttpResponseRedirect(reverse('tunduk:infocom-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))
            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class UnaaRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = INNForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            unaa = Unaa('transportByPin', user=request.user)
            result, response = unaa.postTransportByPin(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте ИНН')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         unaa)

                elif '<ts1:status>203</ts1:status>' in response.text:
                    messages.warning(request, 'Результат не найден. Проверьте ИНН')
                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(request, result, unaa, wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:unaa-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))

            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class MinjystRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = INNForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            minjyst = Minjyst('getSubjectByTin', version=None, user=request.user)
            result, response = minjyst.postSubjectByTin(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте ИНН')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         minjyst)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(request, result, minjyst, wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:minjyst-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))
            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class KadastrRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = ENICodeForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            kadastr = Kadastr(user=request.user)
            response = kadastr.getPropertyPDF(
                form.cleaned_data.get('eni_code'))
            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text or not response.json().get('status'):
                    messages.warning(request, response['message'])
                    tunduk_request_logic(request,
                                         response['message'],
                                         kadastr,
                                         wallet=True)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    response = response.json()
                    file = byte_to_file(response.get('response').get('image'))
                    tunduk_request = tunduk_request_logic(request,
                                                          response.get('response').get('info'),
                                                          kadastr,
                                                          file=file,
                                                          filename=response.get('response').get('name'),
                                                          wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:kadastr-detail',
                                                        args=[tunduk_request.created_at.year,

templates/tunduk/controller.html
{% extends 'base.html' %}{% load static %}
{% block title %}
    Тундук
{% endblock %}
{% block content %}
    <!--Start breadcrumb area-->
    <section class="breadcrumb-area">
        <div class="breadcrumb-area-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="inner-content">
                        <div class="title" data-aos="fade-right" data-aos-easing="linear" data-aos-duration="500">
                            <h2>Тундук</h2>
                        </div>
                        <div class="breadcrumb-menu" data-aos="fade-left" data-aos-easing="linear"
                             data-aos-duration="500">
                            <ul>
                                <li><a href="{% url 'tunduk:tunduk-controller' %}">Главная</a></li>
                                <li class="active">Тундук</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End breadcrumb area-->
    <!--Start Accounts Style1 Area-->
    <section class="account-style1-area">
        <div class="container">
            <div class="row">
                {% if messages %}
                    <div class="alert alert-success">
                        <ul class="messages">
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="sec-title text-center mb-5">
                    <h4>Отправка запросов</h4>
                </div>
                <!--Start Single Account Box Style1-->
                <div class="col-xl-12 col-lg-12">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:tunduk-request' %}">
                            <div class="text-holder">
                                <h3>Получение выписки</h3>
                                <p>Получение выписки из сервисов</p>
                            </div>
                        </a>
                    </div>
                </div>
                <!--End Single Account Box Style1-->
                <div class="sec-title text-center mb-5">
                    <h4>Список выписок из сервисов</h4>
                </div>
            {% if user.company.infocom %}
                <!--Start Single Account Box Style1-->
                <div class="col-xl-4 col-lg-4">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:infocom-list' %}">
                            <div class="text-holder">
                                <h3>Инфоком</h3>
                                <p>Список отправленных запросов</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
                <!--End Single Account Box Style1-->
            {% if user.company.unaa %}
                <!--Start Single Account Box Style1-->
                <div class="col-xl-4 col-lg-4">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:unaa-list' %}">
                            <div class="text-holder">
                                <h3>Унаа</h3>
                                <p>Список отправленных запросов</p>
                            </div>
                        </a>
                    </div>
                </div>
                <!--End Single Account Box Style1-->
            {% endif %}
            {% if user.company.minjyst %}
                <!--Start Single Account Box Style1-->
                <div class="col-xl-4 col-lg-4">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:minjyst-list' %}">
                            <div class="text-holder">
                                <h3>Мин. Юстиции</h3>
                                <p>Список отправленных запросов</p>
                            </div>
                        </a>
                    </div>
                </div>
                <!--End Single Account Box Style1-->
            {% endif %}
            {% if user.company.kadastr %}
                <!--Start Single Account Box Style1-->
                <div class="col-xl-4 col-lg-4">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:kadastr-list' %}">
                            <div class="text-holder">
                                <h3>Кадастр</h3>
                                <p>Список отправленных запросов</p>
                            </div>
                        </a>
                    </div>
                </div>
                <!--End Single Account Box Style1-->
            {% endif %}
            {% if user.company.minselxoz %}
                <!--Start Single Account Box Style1-->
                <div class="col-xl-4 col-lg-4">
                    <div class="single-account-box-style1">
                        <a href="{% url 'tunduk:minselxoz-list' %}">
                            <div class="text-holder">
                                <h3>Мин. Сель. Хоз</h3>
                                <p>Список отправленных запросов</p>
                            </div>
                        </a>
                    </div>
                </div>
                <!--End Single Account Box Style1-->
            {% endif %}
            </div>

        </div>
    </section>
    <!--End Accounts Style1 Area-->

{% endblock %}

templates/tunduk/personal_info.html
{% extends 'base.html' %}{% load static %}{% block title %}Получение выписки{% endblock %}{% block style %}
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">{% endblock %}{% block content %}<!--Start breadcrumb area-->
<section class="breadcrumb-area">
    <div class="breadcrumb-area-bg"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="inner-content">
                    <div class="title" data-aos="fade-right" data-aos-easing="linear" data-aos-duration="500">
                        <h2>Получение выписки</h2>
                    </div>
                    <div class="breadcrumb-menu" data-aos="fade-left" data-aos-easing="linear" data-aos-duration="500">
                        <ul>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Главная</a></li>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Тундук</a></li>
                            <li class="active">Получение выписки</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!--End breadcrumb area--><!--Start Accounts Style1 Area-->
<section class="account-style1-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    <ul class="messagelist">
                        {% for message in messages %}
                            <li {% if message.tags %}class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <ul>
                    {% for key, value in data.items %}
                        <li><b>{{ key }}</b>: {{ value }}</li>
                    {% endfor %}
                </ul>

            </div>
            <div class="col-md-12">
                <ul class="nav nav-tabs">
                    {% if user.company.infocom %}
                        <li class="nav-item">
                            <a href="#infocom" class="nav-link active" data-toggle="tab">Инфоком</a>
                        </li>
                    {% endif %}
                    {% if user.company.unaa %}
                        <li class="nav-item">
                            <a href="#unaa" class="nav-link" data-toggle="tab">Унаа</a>
                        </li>
                    {% endif %}
                    {% if user.company.minjyst %}
                        <li class="nav-item">
                            <a href="#minjyst" class="nav-link" data-toggle="tab">Министерство Юстиции</a>
                        </li>
                    {% endif %}
                    {% if user.company.kadastr %}
                        <li class="nav-item">
                            <a href="#kadastr" class="nav-link" data-toggle="tab">Кадастр</a>
                        </li>
                    {% endif %}
                    {% if user.company.minselxoz %}
                        <li class="nav-item">
                            <a href="#minselxoz" class="nav-link" data-toggle="tab">Мин. Сель. Хоз</a>
                        </li>
                    {% endif %}
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="infocom">
                        <form method="post" action="{% url 'tunduk:infocom-post' %}">
                            {% csrf_token %} {% include "tunduk/form/requestForm.html" with form=form %}
                        </form>
                    </div>
                    <div class="tab-pane fade" id="unaa">
                        <form method="post" action="{% url 'tunduk:unaa-post' %}">
                            {% csrf_token %} {% include "tunduk/form/requestForm.html" with form=unaa_form %}
                        </form>
                    </div>
                    <div class="tab-pane fade" id="minjyst">
                        <form method="post" action="{% url 'tunduk:minjyst-post' %}">
                            {% csrf_token %} {% include "tunduk/form/requestForm.html" with form=unaa_form %}
                        </form>
                    </div>
                    <div class="tab-pane fade" id="kadastr">
                        <form method="post" action="{% url 'tunduk:kadastr-post' %}">
                            {% csrf_token %} {% include "tunduk/form/requestForm.html" with form=eni_form %}
                        </form>
                    </div>
                    <div class="tab-pane fade" id="minselxoz">
                        <form method="post" action="{% url 'tunduk:minselxoz-post' %}">
                            {% csrf_token %} {% include "tunduk/form/requestForm.html" with form=unaa_form %}
                        </form>
                    </div>
                </div>

            </div>

        </div>

    </div>
</section><!--End Accounts Style1 Area-->
<style>
    li.warning {
        font-size: 30px;
        margin: 20px 0;
        color: red;
    }
</style>
{% endblock %}{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>{% endblock %}

templates/tunduk/request_detail.html
{% extends 'base.html' %}{% load static %}{% block title %}Тундук{% endblock %}{% block content %}<!--Start breadcrumb area-->
{% block style %}
<link rel="stylesheet" href="{% static 'css/print.css' %}">{% endblock %}
<section class="breadcrumb-area noprint">
    <div class="breadcrumb-area-bg"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="inner-content">
                    <div class="title" data-aos="fade-right" data-aos-easing="linear" data-aos-duration="500">
                        <h2>{% include 'tunduk/utils/header.html' %}</h2>
                    </div>
                    <div class="breadcrumb-menu" data-aos="fade-left" data-aos-easing="linear" data-aos-duration="500">
                        <ul>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Главная</a></li>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Тундук</a></li>
                            <li><a href="{% include 'tunduk/utils/request_url.html' %}">Список запросов{% include 'tunduk/utils/header.html' %}</a></li>
                            <li class="active">{% include 'tunduk/utils/header.html' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!--End breadcrumb area--><!--Start Accounts Style1 Area-->
<section class="account-style1-area">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 noprint">
                <svg height="20" onclick="print()" class="noprint"><path d="M4,2h8v2h1V1H3v3h1M0,5v6h3v1l3,3h7v-4h3V5m-3,2v1H12v6H6V12H4V8H3V7m2,1h6v1H5m0,1h6v1H5"></path></svg>
            </div>
            <div class="col-xl-12 col-lg-12 print">
                {% include 'tunduk/utils/body.html' %}
            </div>
            <svg height="100" width="100" onclick="print()" class="noprint"><path d="M4,2h8v2h1V1H3v3h1M0,5v6h3v1l3,3h7v-4h3V5m-3,2v1H12v6H6V12H4V8H3V7m2,1h6v1H5m0,1h6v1H5"></path></svg>
        </div>
    </div>
</section><!--End Accounts Style1 Area-->

{% endblock %}

templates/tunduk/request_list.html
{% extends 'base.html' %}{% load static %}{% block title %}{% include 'tunduk/utils/header.html' %}{% endblock %}{% block content %}<!--Start breadcrumb area-->
<section class="breadcrumb-area">
    <div class="breadcrumb-area-bg"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="inner-content">
                    <div class="title" data-aos="fade-right" data-aos-easing="linear" data-aos-duration="500">
                        <h2>{% include 'tunduk/utils/header.html' %}</h2>
                    </div>
                    <div class="breadcrumb-menu" data-aos="fade-left" data-aos-easing="linear" data-aos-duration="500">
                        <ul>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Главная</a></li>
                            <li><a href="{% url 'tunduk:tunduk-controller' %}">Тундук</a></li>
                            <li class="active">{% include 'tunduk/utils/header.html' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!--End breadcrumb area--><!--Start Accounts Style1 Area-->
<section class="account-style1-area">
    <div class="container">
        <div class="sec-title text-center mb-5">
            <h2>Список запрошенных данных</h2>
        </div>
        <div class="row">

            <!--Start Single Account Box Style1-->
            <div class="col-xl-12 col-lg-12">
                {% include 'tunduk/utils/listBody.html' %}
            </div>
            <!--End Single Account Box Style1-->

        </div>

    </div>
</section><!--End Accounts Style1 Area-->

{% endblock %}