apps/tunduk/urls.py
from django.urls import path

from .views import (TundukController,
                    InfocomRequestedList, InfocomRequestedDetail, UnaaRequestedList,
                    UnaaRequestedDetail, MinjystRequestedList, MinjystRequestedDetail,
                    KadastrRequestedDetail, KadastrRequestedList, PersonalInfo, MinSelXozRequestedList,
                    MinSelXozRequestedDetail)

app_name = 'tunduk'

urlpatterns = [
    path('', TundukController.as_view(),
         name='tunduk-controller'),
    path('tunduk-request/', PersonalInfo.as_view(),
         name='tunduk-request'),

    # Инфоком
    path('infocom-list/', InfocomRequestedList.as_view(),
         name='infocom-list'),
    path('infocom-request-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         InfocomRequestedDetail.as_view(),
         name='infocom-detail'),
    path('infocom-request/',
         InfocomRequestedDetail.as_view(),
         name='infocom-post'),

    # Унаа
    path('unaa-list/', UnaaRequestedList.as_view(),
         name='unaa-list'),
    path('unaa-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         UnaaRequestedDetail.as_view(),
         name='unaa-detail'),
    path('unaa-info/', UnaaRequestedDetail.as_view(),
         name='unaa-post'),

    # Министерство Юстиции
    path('minjyst-list/', MinjystRequestedList.as_view(),
         name='minjyst-list'),
    path('minjyst-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         MinjystRequestedDetail.as_view(),
         name='minjyst-detail'),
    path('minjyst-info/', MinjystRequestedDetail.as_view(),
         name='minjyst-post'),

    # Кадастр
    path('kadastr-list/', KadastrRequestedList.as_view(),
         name='kadastr-list'),
    path('kadastr-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         KadastrRequestedDetail.as_view(),
         name='kadastr-detail'),
    path('kadastr-info/', KadastrRequestedDetail.as_view(),
         name='kadastr-post'),

    # Мин сель хоз
    path('minselxoz-list/', MinSelXozRequestedList.as_view(),
         name='minselxoz-list'),
    path('minselxoz-detail/<int:year>/<int:month>/<int:pk>/<uuid:uuid>',
         MinSelXozRequestedDetail.as_view(),
         name='minselxoz-detail'),
    path('minselxoz-info/', MinSelXozRequestedDetail.as_view(),
         name='minselxoz-post'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from apps.accounts.views import reset_password_view

urlpatterns = [
    path('upr/admin/accounts/reset-password/<int:user_id>/', reset_password_view, name='reset_password'),
    path('upr/admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.tunduk.urls', namespace='tunduk')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tunduk/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(
        'Название компании',
        max_length=300
    )
    client_id = models.CharField(
        'ID клиента',
        help_text='ID клиента в тундук, пример: ak_jol_2000',
        max_length=150,
    )
    infocom_secret_key = models.CharField(
        'Секретный ключ клиента',
        help_text='Секретный ключ выдаваемый от Инфоком',
        max_length=150,
    )
    ip_addr = models.CharField(
        'IP Адрес',
        help_text='IP Адрес сервера тундук',
        max_length=30,
    )
    member_code = models.CharField(
        'Код участника тундук',
        help_text='Код участника тундук, пример: 60000165',
        max_length=30,
    )
    subsystem_code = models.CharField(
        'Название участника в тундук',
        help_text='Название участника передаваемый от тундук, пример: akzhol_subsystem',
        max_length=100
    )
    infocom = models.BooleanField(
        default=True,
        verbose_name='Инфоком',
    )
    unaa = models.BooleanField(
        default=False,
        verbose_name='Унаа',
    )
    minjyst = models.BooleanField(
        default=False,
        verbose_name='Мин. Юст',
    )
    kadastr = models.BooleanField(
        default=False,
        verbose_name='Кадастр',
    )
    minselxoz = models.BooleanField(
        default=False,
        verbose_name='Мин. Сель. Хоз',
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

apps/tunduk/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.tunduk.models import Company


class InfocomForm(forms.Form):
    inn = forms.CharField(label='ИНН', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите инн",
            "class": "form-group",
        }
    ))
    passport_series = forms.CharField(label='Серия паспорта', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите номер паспорта",
            "class": "form-group",
        }
    ))
    passport_number = forms.CharField(label='Номер паспорта', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите инн",
            "class": "form-group",
        }
    ))


class INNForm(forms.Form):
    inn = forms.CharField(label='ИНН', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите ИНН",
            "class": "form-group",
        }
    ))


class ENICodeForm(forms.Form):
    eni_code = forms.CharField(label='Код ЕНИ', widget=forms.TextInput(
        attrs={
            "placeholder": "Введите код ЕНИ",
            "class": "form-group",
        }
    ))

    def clean(self):
        super().clean()

        if eni_code := self.cleaned_data.get('eni_code'):
            self.cleaned_data['eni_code'] = eni_code.replace('-', '')

        if not self.cleaned_data['eni_code'].isdigit():
            raise ValidationError('Введите только цифры')

        return self.cleaned_data


class PasswordInputWidget(forms.TextInput):
    input_type = 'password'


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        widgets = {
            'infocom_secret_key': PasswordInputWidget(),
        }

apps/tunduk/views.py
from abc import ABC

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views.generic import TemplateView, ListView, DetailView

from apps.tunduk.forms import InfocomForm, INNForm, ENICodeForm

from apps.history.models import TundukRequestLog

from utils.tunduk.infocom import Infocom
from utils.tunduk.kadastr import Kadastr
from utils.tunduk.minSelXoz import MinSelXoz
from utils.tunduk.tunduk_request_log import tunduk_request_logic
from utils.tunduk.unaa import Unaa
from utils.tunduk.minjyst import Minjyst
from utils.utils import byte_to_file


class TundukController(LoginRequiredMixin, TemplateView):
    template_name = 'tunduk/controller.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Retrieve messages from the messages framework
        messages_list = messages.get_messages(self.request)

        # Pass the messages to the context
        context['messages'] = messages_list

        return context


class PersonalInfo(LoginRequiredMixin, TemplateView):
    template_name = 'tunduk/personal_info.html'
    form = InfocomForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['form'] = InfocomForm()
        context['unaa_form'] = INNForm()
        context['eni_form'] = ENICodeForm()

        return context


class TundukAbstractList(ABC, LoginRequiredMixin, ListView):
    model = TundukRequestLog
    template_name = 'tunduk/request_list.html'

    def get_queryset(self):
        queryset = TundukRequestLog.objects.filter(
            user=self.request.user
        ).order_by('-created_at')
        return queryset


class InfocomRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.INFOCOM)
        return qs


class UnaaRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.UNAA)
        return qs


class MinjystRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.MINJYST)
        return qs


class KadastrRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.KADASTR)
        return qs


class MinSelXozRequestedList(TundukAbstractList):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(request_type=TundukRequestLog.RequestType.MINSELXOZ)
        return qs


class TundukAbstractClass(ABC, LoginRequiredMixin, DetailView):
    model = TundukRequestLog
    template_name = 'tunduk/request_detail.html'


class InfocomRequestedDetail(TundukAbstractClass):

    def post(self, request, *args, **kwargs):
        form = InfocomForm(request.POST, request.FILES)

        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            infocom = Infocom('bankPinService', user=request.user)
            result, response = infocom.post_bankPinService(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте контакт, серию и номер')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         infocom)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(
                        request,
                        result,
                        infocom,
                        result.pop('image'),
                        full_name=f'ФИО: {result.get("surname")} {result.get("name")} {result.get("patronymic")},'
                                  f'ИНН: {result.get("pin")}',
                        wallet=True
                    )

                    return HttpResponseRedirect(reverse('tunduk:infocom-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))
            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class UnaaRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = INNForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            unaa = Unaa('transportByPin', user=request.user)
            result, response = unaa.postTransportByPin(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте ИНН')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         unaa)

                elif '<ts1:status>203</ts1:status>' in response.text:
                    messages.warning(request, 'Результат не найден. Проверьте ИНН')
                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(request, result, unaa, wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:unaa-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))

            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class MinjystRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = INNForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            minjyst = Minjyst('getSubjectByTin', version=None, user=request.user)
            result, response = minjyst.postSubjectByTin(form.cleaned_data)

            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text:
                    message = result.get('Ошибка', 'Результат не найден. Проверьте ИНН')
                    messages.warning(request, message)
                    tunduk_request_logic(request,
                                         message,
                                         minjyst)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    tunduk_request = tunduk_request_logic(request, result, minjyst, wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:minjyst-detail',
                                                        args=[tunduk_request.created_at.year,
                                                              tunduk_request.created_at.month,
                                                              tunduk_request.pk,
                                                              tunduk_request.uuid]))
            else:
                messages.warning(request, "Введите пин в X-Road Тундук")

        return HttpResponseRedirect(reverse('tunduk:tunduk-request'))


class KadastrRequestedDetail(TundukAbstractClass):
    def post(self, request, *args, **kwargs):
        form = ENICodeForm(request.POST)
        if form.is_valid():
            # Получение данных из СМЭВ Тундук
            kadastr = Kadastr(user=request.user)
            response = kadastr.getPropertyPDF(
                form.cleaned_data.get('eni_code'))
            if response:
                # Проверка на ошибку со стороные СМЭВ "Тундук"
                if 'faultcode' in response.text or not response.json().get('status'):
                    messages.warning(request, response['message'])
                    tunduk_request_logic(request,
                                         response['message'],
                                         kadastr,
                                         wallet=True)

                # Проверка успешности запроса
                elif response.status_code == 200:
                    response = response.json()
                    file = byte_to_file(response.get('response').get('image'))
                    tunduk_request = tunduk_request_logic(request,
                                                          response.get('response').get('info'),
                                                          kadastr,
                                                          file=file,
                                                          filename=response.get('response').get('name'),
                                                          wallet=True)

                    return HttpResponseRedirect(reverse('tunduk:kadastr-detail',
                                                        args=[tunduk_request.created_at.year,

templates/tunduk/form/infocomData.html
{% load static %}
<h4 class="main-print-header">Выписка из электронных сервисов Государственных органов Кыргызской Республики</h4>
<div class="flex-container">
    <div class="left-column">
        <!-- Добавляем изображение гражданина в левую колонку -->
        <img src="{% if object.file %}{{object.file.url}}{% else %}{% static 'images/source/no-img.gif' %}{% endif %}" alt="Изображение гражданина {{object.data.name}}">
    </div>
    <div class="right-column">
        <p><span>ПИН:</span> <span class="rigth-text">{{object.data.pin}}</span></p>
        <p><span>Фамилия:</span> <span class="rigth-text">{{object.data.surname}}</span></p>
        <p><span>Имя:</span> <span class="rigth-text">{{object.data.name}}</span></p>
        <p><span>Отчество:</span> <span class="rigth-text">{{object.data.patronymic}}</span></p>
        <p><span>Пол:</span> <span class="rigth-text">{{object.data.gender}}</span></p>
        <p><span>Дата рождения:</span> <span class="rigth-text">{{object.data.dateOfBirth}}</span></p>
        <p><span>Номер документа: {{object.data.passportSeries}}</span> <span class="rigth-text">{{object.data.passportNumber}}</span>
        </p>
        <p><span>Дата выдачи:</span> <span class="rigth-text">{{object.data.issuedDate}}</span></p>
        <p><span>Срок действия:</span> <span class="rigth-text">{{object.data.expiredDate}}</span></p>
        <p><span>Семейное положение:</span> <span class="rigth-text">{{object.data.maritalStatus}}</span></p>
        <p><span>Адрес регистрации:</span> <span>{{object.data.message}}</span></p>
    </div>
</div>
<hr>
<div class="addr-container">
    <h6 class="print-header">Информация из АИС «Санарип Аймак»</h6>
    <div>
        <p>Фактический адрес: {% if object.data.sanarip %}{{object.data.sanarip.address}}{% endif %}</p>
    </div>
</div>

<hr><h6 class="print-header">Состав семьи</h6>
<table>
    <tr>
        <td>№</td>
        <td>Ф.И.О.</td>
        <td>Вид отношений</td>
    </tr>
    {% for member in object.data.sanarip.members %}
        <tr>
            <td></td>
            <td>{{member.name}}</td>
            <td>{{member.role}}</td>
        </tr>
    {% endfor %}
</table>

<p class="note">Примечание: Сведения, содержащие в настоящей электронной выписке, являются актуальными на дату
    запроса!</p>
<p class="footer"><b>Дата запроса:</b> {{object.created_at|date:'d M Y H:i'}}<br><b>Распечатано:</b>
    {% now 'd M Y H:i' %}<br><b>Пользователь:</b>
    {{object.user.get_full_name}} </p>

<style>
    h4 {
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #000;
    }

    td {
        padding: 1px;
        text-align: center;
    }

    th {
        padding: 10px;
        text-align: center;
        font-size: 12px;
    }

    th {
        background-color: #f2f2f2;
    }

    .note {
        margin-top: 10px;
        font-style: italic;
    }

    .footer {
        margin-top: 20px;
        text-align: right;
        font-size: 12px;
    }

    .flex-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 20px;
    }

    .addr-container {
        display: flex;
        flex-direction: column;
    }

    .left-column {
        border: 1px solid black;
        padding: 5px;
        margin: 10px;
    }

    .rigth-text {
        float: right;
    }

    .print-header {
        padding: 10px 0;
        background: #eee;
        print-color-adjust: inherit;
    }

</style>

templates/tunduk/form/infocomTable.html
{% load static %}
<table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ФИО</th>
                        <th scope="col">ИНН</th>
                        <th scope="col">Паспортные данныеы</th>
                        <th scope="col">Пол</th>
                        <th scope="col">День рожения</th>
                        <th scope="col">Фото</th>
                        <th scope="col">Дата запроса</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ object.id }}</th>
                        <td>{{ object.user }}</td>
                        <td>{{ object.data.pin }}</td>
                        <td>{{ object.data.passportSeries }} {{ object.data.passportNumber }}</td>
                        <td>{% if object.data.gender == 'F' %}Ж{% else %}{{ object.data.gender }}{% endif %}</td>
                        <td>
                            {{object.data.dateOfBirth }}
                        </td>
                        <td>
                            <img src="{% if object.file %}{{ object.file.url }}{% else %}{% static 'images/source/no-img.gif' %}{% endif %}"
                                 alt="" style="width: 50px">
                        </td>
                        <td>{{object.created_at}}</td>
                        <td><a href="{{object.get_absolute_url}}" class="btn-one">Подробнее</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

templates/tunduk/form/kadastrData.html
{% load static %}
<h4 class="main-print-header">Выписка из электронных сервисов Государственных органов Кыргызской Республики</h4>
<h6 class="print-header">Информация из Единого государственного реестра прав на недвижимое имущество</h6>
<div class="col-xl-12 col-lg-12 print">
    <a href="{{object.file.url}}" target="_blank" class="btn-one btn btn-block noprint">Скачать файл</a>
    <hr>
    <table class="table table-hover">
        <tr>
            <th scope="col">Идентификационный код единицы недвижимого имущества</th>
            <td>{{object.data.propCode}}</td>
        </tr>
        <tr>
            <th scope="col">Адрес</th>
            <td>{{object.data.address}}</td>
        </tr>
        <tr>
            <th scope="col">Форма собственности</th>
            <td>{{object.data.ownForm}}</td>
        </tr>
        <tr>
            <th scope="col">Вид недвижимости</th>
            <td>{{object.data.type}}</td>
        </tr>
        <tr>
            <th scope="col">Форма использования</th>
            <td>{{object.data.forType}}</td>
        </tr>
        <tr>
            <th scope="col">Целевое назначение</th>
            <td>{{object.data.forUseType}}</td>
        </tr>
    </table>
</div>
<hr>

<p class="note">Примечание: Сведения, содержащие в настоящей электронной выписке, являются актуальными на дату
    запроса!</p>
<p class="footer"><b>Дата запроса:</b> {{object.created_at|date:'d M Y H:i'}}<br><b>Распечатано:</b>
    {% now 'd M Y H:i' %}<br><b>Пользователь:</b>
    {{object.user.get_full_name}} </p>

<style>
    h4 {
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #000;
    }

    td {
        padding: 1px;
        text-align: center;
    }

    th {
        padding: 10px;
        text-align: center;
        font-size: 12px;
    }

    th {
        background-color: #f2f2f2;
    }

    .note {
        margin-top: 10px;
        font-style: italic;
    }

    .footer {
        margin-top: 20px;
        text-align: right;
        font-size: 12px;
    }
    .print-header {
        padding: 10px 0;
        background: #eee;
        print-color-adjust: inherit;
    }
</style>

templates/tunduk/form/kadastrTable.html
<table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ФИО</th>
                        <th scope="col">Идентификационный код единицы недвижимого имущества</th>
                        <th scope="col">Адрес</th>
                        <th scope="col">Дата запроса</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ object.id }}</th>
                        <td>{{ object.user }}</td>
                        <td>{{ object.data.propCode }}</td>
                        <td>{{ object.data.address }}</td>
                        <td>{{object.created_at}}</td>
                        <td><a href="{% url 'tunduk:kadastr-detail' object.created_at.year object.created_at.month object.pk object.uuid %}"
                               class="btn-one">Подробнее</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

templates/tunduk/form/minjystData.html
{% load static %}
<h4 class="main-print-header">Выписка из электронных сервисов Государственных органов Кыргызской Республики</h4>
<h6 class="print-header">Информация из Министерства Юстиции</h6>
<div class="col-xl-12 col-lg-12 print">
    <hr>
    <table class="table table-hover">
        <tr>
            <th scope="col">Полное наименование на государственном языке</th>
            <td>{{object.data.fullNameGl}}</td>
        </tr>
        <tr>
            <th scope="col">Полное наименование на официальном языке</th>
            <td>{{object.data.fullNameOl}}</td>
        </tr>
        <tr>
            <th scope="col">Регистрационный код минюста</th>
            <td>{{object.data.registrCode}}</td>
        </tr>
        <tr>
            <th scope="col">ОКПО</th>
            <td>{{object.data.statSubCode}}</td>
        </tr>
        <tr>
            <th scope="col">ИНН</th>
            <td>{{object.data.tin}}</td>
        </tr>
        <tr>
            <th scope="col">Регион (область)</th>
            <td>{{object.data.region}}</td>
        </tr>
        <tr>
            <th scope="col">Район</th>
            <td>{{object.data.district}}</td>
        </tr>
        {% if object.data.city %}
        <tr>
            <th scope="col">Город</th>
            <td>{{object.data.city}}</td>
        </tr>
        {% endif %}
        {% if object.data.vilage %}
        <tr>
            <th scope="col">Село</th>
            <td>{{object.data.vilage}}</td>
        </tr>
        {% endif %}
        {% if object.data.microdistrict %}
        <tr>
            <th scope="col">Микрорайон</th>
            <td>{{object.data.microdistrict}}</td>
        </tr>
        {% endif %}
        <tr>
            <th scope="col">Улица</th>
            <td>{{object.data.street}}</td>
        </tr>
        <tr>
            <th scope="col">Дом</th>
            <td>{{object.data.house}}</td>
        </tr>
        <tr>
            <th scope="col">Номер телефона</th>
            <td>{{object.data.phones}}</td>
        </tr>
        <tr>
            <th scope="col">Электронная почта</th>
            <td>{{object.data.email1}}</td>
        </tr>
        <tr>
            <th scope="col">Руководитель</th>
            <td>{{object.data.chief}}</td>
        </tr>
        <tr>
            <th scope="col">Дополнительное текстовое описание (примечание)</th>
            <td>{{object.data.description}}</td>
        </tr>
    </table>
</div>
<hr>

<p class="note">Примечание: Сведения, содержащие в настоящей электронной выписке, являются актуальными на дату
    запроса!</p>
<p class="footer"><b>Дата запроса:</b> {{object.created_at|date:'d M Y H:i'}}<br><b>Распечатано:</b>
    {% now 'd M Y H:i' %}<br><b>Пользователь:</b>
    {{object.user.get_full_name}} </p>

<style>
    h4 {
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #000;
    }

    td {
        padding: 1px;
        text-align: center;
    }

    th {
        padding: 10px;
        text-align: center;
        font-size: 12px;
    }

    th {
        background-color: #f2f2f2;
    }

    .note {
        margin-top: 10px;
        font-style: italic;
    }

    .footer {
        margin-top: 20px;
        text-align: right;
        font-size: 12px;
    }
    .print-header {
        padding: 10px 0;
        background: #eee;
        print-color-adjust: inherit;
    }
</style>

templates/tunduk/form/minjystTable.html
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">ФИО</th>
        <th scope="col">Полное наименование компании</th>
        <th scope="col">Дата запроса</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <th scope="row">{{ object.id }}</th>
        <td>{{ object.user }}</td>
        <td>{{ object.data.fullNameOl }}</td>
        <td>{{object.created_at}}</td>
        <td><a href="{% url 'tunduk:minjyst-detail' object.created_at.year object.created_at.month object.pk object.uuid %}"
                class="btn-one">Подробнее</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/tunduk/form/minselxozTable.html
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО</th>
            <th scope="col">ИНН</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <th scope="row">{{ object.id }}</th>
            <td>{{ object.user }}</td>
            <td>{{ object.data.inn }}</td>
            <td><a href="{% url 'tunduk:minselxoz-detail' object.created_at.year object.created_at.month object.pk object.uuid %}"
                    class="btn-one">Подробнее</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/tunduk/form/requestForm.html
{% load crispy_forms_tags %}

<!--Start Single Account Box Style1-->
    {% for field in form.visible_fields %}
        <div class="form-group" style="margin-bottom:10px">
            <div class="input-box">
                {{ field|as_crispy_field }}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>

    {% endfor %}

<!--End Single Account Box Style1-->
<button class="btn-one btn btn-block" type="submit">
    <span class="txt">
        Получить данные
    </span>
</button>